GET http://localhost:5504/
Accept: application/json
Authorization: Bearer <your-access-token>
x-platform: yu2ahel


###

GET http://localhost:5502/demo
Accept: application/json
Authorization: Bearer <your-access-token>
x-platform: yu2ahel

###
